repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        - id: end-of-file-fixer
        - id: trailing-whitespace

    - repo: https://github.com/myint/autoflake
      rev: v2.3.1
      hooks:
        - id: autoflake
          files: (^(src|tests)/)|(^[^/]*$)
          args: [--in-place, --remove-all-unused-imports, --recursive, --ignore-init-module-imports]

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
        - id: black
          language_version: python3.9

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          name: isort (python)
