repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        - id: end-of-file-fixer
        - id: trailing-whitespace

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.12.4
      hooks:
        # Run the linter.
        - id: ruff-check
          types_or: [ python, pyi ]
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
          types_or: [ python, pyi ]
